language: php
php:
  - "5.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install alien dpkg-dev debhelper build-essential asterisk php5 apache2 php5-cli php-pear php5-mysql libapache2-mod-fastcgi -qq
  - sudo rm -Rf /etc/asterisk/*
  - sudo pear install db
  - sudo chown $USER /var/run/asterisk
  - sudo chown -R $USER /etc/asterisk
  - sudo chown -R $USER /var/{lib,log,spool}/asterisk
  - sudo chown -R $USER /usr/lib/asterisk
  - sudo mkdir /var/www/html
  - sudo chown -R $USER /var/www/
  - mysqladmin -u root create asterisk
  - mysqladmin -u root create asteriskcdrdb
  - mysql -u root -e "GRANT ALL PRIVILEGES ON asterisk.* TO asteriskuser@localhost IDENTIFIED BY 'amp109';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO asteriskuser@localhost IDENTIFIED BY 'amp109';"
  - mysql -u root -e "flush privileges;"
  - sudo ./start_asterisk start
install:
  - sudo ./install_amp --installdb --skip-module-install --scripted --username asteriskuser --password amp109 --dbhost localhost
  - sudo amportal a r
  - ls /etc/asterisk
before_script:
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - sudo chmod 777 /etc/freepbx.conf
  - sudo chmod 777 -R /var/www
  - sudo chmod 777 -R /etc/asterisk
  - sudo usermod -a -G asterisk travis
script: 
  - phpunit tests
  - phpunit amp_conf/htdocs/admin/libraries/BMO/Tests/CronTest.php
  - phpunit amp_conf/htdocs/admin/libraries/BMO/Tests/DBHelperTest.php
  - phpunit amp_conf/htdocs/admin/libraries/BMO/Tests/GPGTest.php
  - phpunit amp_conf/htdocs/admin/libraries/BMO/Tests/ModulesTest.php
  - phpunit amp_conf/htdocs/admin/libraries/BMO/Tests/RequestTest.php