language: php
php:
  - "5.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install asterisk php5 apache2 php5-cli php-pear -qq
  - sudo sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php5/apache2/php.ini
  - sudo cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf_orig
  - sudo sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/apache2/apache2.conf
  - sudo service apache2 start
  - sudo pear install db
  - sudo adduser asterisk --disabled-password --no-create-home --gecos "Asterisk User"
  - sudo chown asterisk. /var/run/asterisk
  - sudo chown -R asterisk. /etc/asterisk
  - sudo chown -R asterisk. /var/{lib,log,spool}/asterisk
  - sudo chown -R asterisk. /usr/lib/asterisk
  - sudo mkdir /var/www/html
  - sudo chown -R asterisk. /var/www/
  - mysqladmin -u root create asterisk -p
  - mysqladmin -u root create asteriskcdrdb -p
  - mysql -u root asterisk -p < SQL/newinstall.sql 
  - mysql -u root asteriskcdrdb -p < SQL/cdr_mysql_table.sql
  - mysql -u root -p -e "GRANT ALL PRIVILEGES ON asterisk.* TO asteriskuser@localhost IDENTIFIED BY 'amp109';"
  - mysql -u root -p -e "GRANT ALL PRIVILEGES ON asteriskcdrdb.* TO asteriskuser@localhost IDENTIFIED BY 'amp109';"
  - mysql -u root -p -e "flush privileges;"
  - sudo ./start_asterisk start